name: Build and Deploy CV

concurrency:
  group: cv-build-and-deploy
  cancel-in-progress: true

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - CV.md
      - .github/workflows/build-pages.yml
      - templates/template.html

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install patched wkhtmltopdf
        run: |
          curl -L -o wkhtmltox.deb https://github.com/wkhtmltopdf/packaging/releases/download/0.12.6-1/wkhtmltox_0.12.6-1.bionic_amd64.deb
          sudo apt-get update
          sudo apt-get install -y ./wkhtmltox.deb
          wkhtmltopdf --version


      - name: Create output directory
        run: mkdir -p output

      - name: Convert Markdown to HTML - CV
        run: |
          pandoc CV.md \
            --template=templates/template.html \
            --metadata title="Steven Lawton - CV" \
            -f markdown -t html5 -s -o output/index.html

      - name: Convert Markdown to HTML - CV(pdf version)
        run: |
          pandoc CV.md \
            --template=templates/template.cv.html.html \
            --metadata title="Steven Lawton - CV" \
            --lua-filter=templates/wrap-experience.lua \
            -f markdown -t html5 -s -o output/index.cv.html

      - name: Convert Markdown to HTML - profile
        run: |
          pandoc profile.md \
            --template=templates/template.profile.html \
            --metadata title="Steven Lawton – Profile" \
            -f markdown -t html5 -s -o output/profile.html

      - name: Convert HTML to PDF - CV
        run: |
          /usr/local/bin/wkhtmltopdf output/index.cv.html output/Steven-Lawton-CV.pdf

      - name: Insert download link at marker
        run: |
          sed -i 's|<!-- PDF-LINK-HERE -->|<p><a href="/stevenlawton/Steven-Lawton-CV.pdf" download>📄 Download PDF version</a></p>|' output/index.html

      - name: Convert HTML to PDF - Profile
        run: |
          wkhtmltopdf output/profile.html output/Steven-Lawton-Profile.pdf

      - name: Upload output files for deployment
        uses: actions/upload-artifact@v4
        with:
          name: site
          path: output/

  commit-pdfs:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Required to make commits

      - name: Download built site
        uses: actions/download-artifact@v4
        with:
          name: site
          path: output

      - name: Copy PDF to assets/
        run: |
          mkdir -p assets
          cp output/Steven-Lawton-CV.pdf assets/Steven-Lawton-CV.pdf          
          cp output/Steven-Lawton-Profile.pdf assets/Steven-Lawton-Profile.pdf          

      - name: Commit PDF
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
          git add -f assets/Steven-Lawton-CV.pdf
          git add -f assets/Steven-Lawton-Profile.pdf
          if ! git diff --cached --quiet; then
            git commit -m "Update PDF version of CV/Profile"
            git push
          else
            echo "No changes to commit."
          fi

  publish:
    needs: [build, commit-pdfs]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository (for context)
        uses: actions/checkout@v4

      - name: Download built site
        uses: actions/download-artifact@v4
        with:
          name: site
          path: output

      - name: List contents of output directory
        run: |
          echo "=== Listing output directory ==="
          ls -la output
          echo "=== Listing output/pdf ==="
          ls -la output/*.pdf || true
          echo "=== Listing output/html ==="
          cat output/index.html || echo "No CV HTML found"
          cat output/profile.html || echo "No Profile HTML found"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./output
          publish_branch: gh-pages
