name: Build and Deploy CV

concurrency:
  group: cv-build-and-deploy
  cancel-in-progress: true

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - CV.md
      - .github/workflows/build-pages.yml
      - templates/template.html

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Pandoc and wkhtmltopdf
        run: sudo apt-get update && sudo apt-get install -y pandoc wkhtmltopdf

      - name: Create output directory
        run: mkdir -p output

      - name: Convert Markdown to HTML
        run: |
          pandoc CV.md \
            --template=templates/template.html \
            --metadata title="Steven Lawton – CV" \
            -f markdown -t html -s -o output/index.html

      - name: Convert Markdown to PDF
        run: |
          pandoc CV.md \
            --metadata title="Steven Lawton – CV" \
            -t html5 \
            -s -o output/Steven-Lawton-CV.pdf \
            --pdf-engine=wkhtmltopdf

      - name: Upload output files for deployment
        uses: actions/upload-artifact@v4
        with:
          name: site
          path: output/

  commit-pdf:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Required to make commits

      - name: Download built site
        uses: actions/download-artifact@v4
        with:
          name: site
          path: output

      - name: Copy PDF to assets/
        run: |
          mkdir -p assets
          cp output/Steven-Lawton-CV.pdf assets/Steven-Lawton-CV.pdf          

      - name: Commit PDF
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
          git add -f assets/Steven-Lawton-CV.pdf
          if ! git diff --cached --quiet; then
            git commit -m "Update PDF version of CV"
            git push
          else
            echo "No changes to commit."
          fi

  publish:
    needs: [build, commit-pdf]
    runs-on: ubuntu-latest
    steps:
      - name: Download built site
        uses: actions/download-artifact@v4
        with:
          name: site
          path: output

      - name: Debug output contents
        run: ls -l output/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./output
