name: Build and Deploy CV

concurrency:
  group: cv-build-and-deploy
  cancel-in-progress: true

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - CV.md
      - .github/workflows/build-pages.yml
      - templates/template.html

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-html:

    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Pandoc
        run: sudo apt-get update && sudo apt-get install -y pandoc

      - name: Create output directory
        run: mkdir -p output

      - name: Convert Markdown to HTML
        run: |
          pandoc CV.md \
            --template=templates/template.html \
            --metadata title="Steven Lawton – CV" \
            -f markdown -t html -s -o output/index.html


  build-pdf:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Pandoc and wkhtmltopdf
        run: sudo apt-get update && sudo apt-get install -y pandoc wkhtmltopdf

      - name: Create output directory
        run: mkdir -p output

      - name: Convert Markdown to PDF
        run: |
          pandoc CV.md \
            --metadata title="Steven Lawton – CV" \
            -t html5 \
            -s -o output/Steven-Lawton-CV.pdf \
            --pdf-engine=wkhtmltopdf

      - name: Commit PDF to assets/
        run: |
          mkdir -p assets
          cp output/Steven-Lawton-CV.pdf assets/Steven-Lawton-CV.pdf

          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add assets/Steven-Lawton-CV.pdf
          git diff --quiet || git commit -m "Update PDF version of CV"
          git push

  publish-html:
    needs: [build-html, build-pdf]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./output
